### ISSUE TITLE
Missing AUTHORS file

### ISSUE THREAD

**Issue by touilleMan** [bitlogik/guardata#3]
Hi (again ^^)

The Parsec AUTHORS file shouldn't be removed as it is there to credit the people who worked on the project. This is especially important given the fork didn't retain the git commits history of the original project.

**Comment by bitlogik** [comment]
Hi,

We can temporary point to Scille/parsec-cloud/contributor, but when a new person will contribute to parsec-cloud, he will be listed as a guardata contributor.

To solve this issue, and preserve the author attributions, we will maintain an author list in the AUTHORS files. The format will be the following :
Surname NAME  @HandleGithub

Can you confirm and fill out this list about your colleagues :
Emmanuel LEBLOND   @touilleMan
Vincent MICHEL     @vxgmichel
Maxime GRANDCOLAS  @Max-7
?? ??              @c4ffein
Antoine DUPRÉ      @AntoineDupre
Valérie MONTÉ      @vamonte
?? ??              @Sithi5
?? ??              @Ironicbay
Julie ROSSI        @JulieRossi
David DELASSUS     @linkdd
Stefan CONTIU      @stefan-contiu

**Comment by touilleMan** [comment]
yep that's fine by me

The names your are missing:
```
Charles Pellegrini @c4ffein
Malo Boucé @Sithi5
Alban Costaz @Ironicbay
Valentin MONTÉ @vamonte
```

**Comment by bitlogik** [comment]
Thanks.
And sorry for Valentin ! 😄
